name: habito_de_ler
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^1.2.0
  intl: 0.15.8
  google_sign_in: ^4.0.7
  cloud_firestore: ^0.11.0+1
  firebase_core: ^0.4.0
  firebase_auth: ^0.11.0
  cached_network_image: ^1.0.0
  shared_preferences: 0.5.2
  ant_icons: ^1.0.0
  http: ^0.12.0+2
  shimmer: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^1.3.0
  mockito: ^4.1.1


flutter:
  assets:
    - images

  uses-material-design: true

